name: Publish release

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build

    - name: Get build info
      run: |
        ARTIFACT_NAME=$(ls ./lib/build/libs)
        echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_ENV
        echo "TAG_NAME=$(echo $ARTIFACT_NAME | grep -oP '^.*v[\d]\.[\d]')" >> $GITHUB_ENV
        echo "TAG_VERSION=$(echo $TAG_NAME | grep -o 'v.*')" >> $GITHUB_ENV

    - name: Publish release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.TAG_NAME }}
        name: Juno ${{ env.TAG_VERSION }}
        files: ${{ env.ARTIFACT_NAME }}
        body_path: ./CHANGELOG.md



